name: Daily Commented Tasks Report

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual run via GitHub UI

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub pandas openpyxl

    - name: Run report generator
      env:
        GH_PAT: ${{ secrets.GH_PAT }}   # ✅ Your actual token is named GH_PAT
      run: python generate_report.py

    - name: Commit report to repo
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        today=$(date +'%Y-%m-%d')
        filename="daily_commented_tasks_${today}.xlsx"

        git add "$filename"
        git commit -m "📋 Daily commented tasks report - $today" || echo "No changes to commit"
        git push
