name: Daily Commented Tasks Report

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:     

permissions:
  contents: write       

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub pandas openpyxl

    - name: Run report generator
      env:
        GH_PAT: ${{ secrets.GH_PAT }}  # Ensure this secret is set if needed
      run: python .github/workflows/generate_report.py

    - name: Commit and push report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-provided by GitHub Actions
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        today=$(date +'%Y-%m-%d')
        filename="daily_commented_tasks_${today}.xlsx"

        git add "$filename"
        git commit -m "📋 Daily commented tasks report - $today" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
